trigger:
- master

schedules:
- cron: "0 0 11 * * ?"
  displayName: "Daily 11am"
  branches:
    include: [ "master" ]
  always: true
  batch: true

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  submodules: true
  clean: true

- task: "giuliovdev.hugo-extension.hugo-build-task-v2.HugoTask@2"
  inputs:
    source: '$(Build.SourcesDirectory)'
    destination: '$(Build.ArtifactStagingDirectory)'
    hugoVersion: '0.88.0'
    additionalArgs: '--baseURL https://bizzeh.com/ --minify'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'content'
    publishLocation: 'Container'