trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  submodules: true
  clean: true
- task: HugoTask@2
  inputs:
    source: '$(Build.SourcesDirectory)'
    destination: '$(Build.ArtifactStagingDirectory) --minify'
    hugoVersion: '0.88.0'
    additionalArgs: '--baseURL https://bizzeh.com/'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'content'
    publishLocation: 'Container'