baseURL = "https://www.bizzeh.com/"
languageCode = "en-gb"
title = "The Angry Dev"
googleAnalytics = "UA-3629904-1"
theme = "hyde"
DisqusShortname = "bizzeh"

[Author] 
  name = "Darren"

[params]
  description = "Tutorials, guides, explanations and ramblings from a very angy man"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/bizzehdee/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/bizzehdee/"}
  ]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "author"