baseURL = "https://www.darrenhorrocks.co.uk/"
languageCode = "en-gb"
title = "The Angry Dev"
googleAnalytics = "UA-3629904-1"
theme = "hyde"
DisqusShortname = "bizzeh"
enableRobotsTXT = true

[Author] 
  name = "darren horrocks"

[params]
  description = "Darren Horrocks explains various Programming and DevOps practices, with some guides, explanations and ramblings from a sometimes angry man"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/bizzehdee/"},
      {Name = "Twitch", URL = "https://www.twitch.tv/bizzehdee"},
      {Name = "YouTube", URL = "https://www.youtube.com/@bizzehdee"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/bizzehdee"}
  ]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "author"

[outputs]
home = ["HTML","FEED"]

[mediaTypes]
[mediaTypes."application/rss"]
suffixes = ["xml"]

[outputFormats]
[outputFormats.FEED]
mediatype = "application/rss"
baseName = "feed"

[markup.goldmark.renderer]
unsafe= true
