baseURL = "https://bizzeh.com/"
languageCode = "en-gb"
title = "The Angry Dev"
googleAnalytics = "UA-3629904-1"
theme = "hyde"
DisqusShortname = "bizzeh"

[Author] 
  name = "darren"

[params]
  description = "Programming and DevOps tutorials, guides, explanations and ramblings from a sometimes angy man"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/bizzehdee/"},
      {Name = "YouTube", URL = "https://www.youtube.com/channel/UCjGZwgZxkZDceaPXt84ndKw"}
  ]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "author"

[outputs]
home = ["HTML","FEED"]

[mediaTypes]
[mediaTypes."application/rss"]
suffixes = ["xml"]

[outputFormats]
[outputFormats.FEED]
mediatype = "application/rss"
baseName = "feed"

[markup.goldmark.renderer]
unsafe= true